
MODEL_CONFIG:
  IMG_SIZE: 512

TRAINING_CONFIG:

  EPOCH: 100
  DOMAIN : 'ch' # bags
  BATCH_SIZE: 16


  # lr and lambda
  LR : 5e-6
  LAMBDA_CLS  : 1.0

  # Optimizer
  OPTIM : ADAM
  BETA1: 0.5
  BETA2: 0.999

  # Settings
  NUM_WORKER : 4
  MODE : 'train'
  CPU_SEED : 123
  GPU_SEED : 456
  USE_TENSORBOARD : 'False' # 'True' or 'False'

  # Directory
  IMG_DIR : 'paint_img' #'data'
  TRAIN_DIR : 'edge_segmentation_tutorial'
  LOG_DIR : 'logs'
  SAMPLE_DIR : 'samples'
  RESULT_DIR : 'results'
  MODEL_DIR : 'models'

  # GPU
  GPU: 0

  # Step Size

  SAMPLE_STEP : 1 # epoch based
  LOG_STEP : 100 # iteration based
  SAVE_STEP : 5 # epoch based
  SAVE_START : 10
  LR_DECAY_STEP : 20

TEST_CONFIG:
  TEST_EPOCH : 100


